package com.fris.boardportal.audit;

public enum AuditAction {
    ORGANIZATION_SIGNUP,
    LOGIN,
    USER_CREATED,
    USER_UPDATED,
    MEETING_CREATED,
    MEETING_UPDATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    RESOLUTION_CREATED,
    RESOLUTION_OPENED,
    RESOLUTION_CLOSED,
    RESOLUTION_DELETED,
    VOTE_CAST,
    ACTION_ITEM_CREATED,
    ACTION_ITEM_STATUS_CHANGED,
    ACTION_ITEM_DELETED,
    COMMENT_POSTED,
    COMMENT_DELETED
}
