package com.fris.boardportal.audit;

public enum AuditAction {
    ORGANIZATION_SIGNUP,
    LOGIN,
    USER_CREATED,
    USER_UPDATED,
    MEETING_CREATED,
    MEETING_UPDATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    RESOLUTION_CREATED,
    RESOLUTION_OPENED,
    RESOLUTION_CLOSED,
    RESOLUTION_DELETED,
    VOTE_CAST
}
